dBildungsplattform/dbildungs-iam-keycloak

Dockerfile

Keycloak upgrade to version 21.1.2 to fix security issues.
https://ticketsystem.dbildungscloud.de/browse/EW-562

EW-562 Upgrade Keycloak to v21.1.2

---

.github/workflows/chart-release-manual.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

- user version 5 to fix pull image error (length of sha has to be consistent 7, not 8)

DBP-559-fix-rollout-of-helm-charts

---

charts/dbildungscloud-iam-keycloak/templates/deployment.yaml

Fixes deployment.yaml to not repeat things that already are in the entrypoint and thus cause an error

Adjust deployment to different entrypoint

---

charts/dbildungscloud-iam-keycloak/dev-realm-spsh.json
charts/dbildungscloud-iam-keycloak/templates/deployment.yaml

Added necessary run time probes
Reactivated Admin-Client (forgot on last merge)

Spsh 344 probes

---

charts/dbildungscloud-iam-keycloak/dev-realm-spsh.json
charts/dbildungscloud-iam-keycloak/templates/deployment.yaml

Added admin client to SPSH realm

---

Dockerfile

We need both WebAuthn and CIBA for production scenarios. If they're disabled our realm as configured will not run error-free

Both WebAuthn and CIBA are needed for production scenarios

---

Dockerfile

Spsh 405 enable webauthn

---

charts/dbildungscloud-iam-keycloak/templates/ingress.yaml

DBP-615-keycloak-ingress-adjustments

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

- add a description and rename workflwo file - so it is easier to have an overview of failed jobs in the PR overview

DBP-631-rename-workflow-file

---

.github/workflows/chart-release-manual.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

Dbp 625 update spsh to use a new versioning

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-623 Cross branch rollout

---

charts/dbildungs-iam-keycloak/values.yaml

SPSH-489-Adjust Resources requested to something sensible

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-696 Make deploy inherit secrets

---

.github/workflows/create-release.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
build-dev.sh

- add GHA to release image and helm chart and limit Dev Pipeline

DBP-679-create-release-gha

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-647-small-improvements

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json

Enable CORS for everyone with a valid redirect-URL
https://ticketsystem.dbildungscloud.de/browse/SPSH-521

Configured KC such that every source of a valid redirect is CORS-Enabled

---

charts/dbildungs-iam-keycloak/templates/deployment.yaml

OPS-6294-add-username-to-deployment-envs

---

.github/workflows/create-release.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

Ops-6248-upgrade-image-publish-version

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

Reference deploy.yaml with tag 4.0.0

Dbp 757 playwright tests

---

README.md
charts/dbildungs-iam-keycloak/dev-realm-spsh.json

Adds steup flow to keycloak and assigns it to the spsh client.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-670

SPSH-670: LOA Step-Up Flow

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json

Give SPSH-Admin the right to manage the realm (Needed to create groups/roles)

SPSH-663 Add manage-realm role to admin client

---

src/themes/schulportal/login/template.ftl

changed test dev links to staging
https://ticketsystem.dbildungscloud.de/browse/SPSH-802

spsh 802 changed test dev links to staging

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json

Added a test client to the realm configuration for the test environment.
Separated the realm configuration for test and staging/prod environments so that the test client cannot be deployed to staging/prod.
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/572

SPSH-543: Client für Swagger mit längeren Timeouts

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-952-improvements-database-deletion-job

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json
charts/dbildungs-iam-keycloak/templates/deployment.yaml
charts/dbildungs-iam-keycloak/templates/secret.yaml
charts/dbildungs-iam-keycloak/values.yaml

Add new itslearning client

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json
charts/dbildungs-iam-keycloak/templates/deployment.yaml
charts/dbildungs-iam-keycloak/templates/secret.yaml
charts/dbildungs-iam-keycloak/values.yaml

Add client for OX.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-984

SPSH-984: OIDC-Client für OX einrichten

---

Dockerfile
charts/dbildungs-iam-keycloak/templates/configmap.yaml
charts/dbildungs-iam-keycloak/templates/deployment.yaml
charts/dbildungs-iam-keycloak/templates/service.yaml
charts/dbildungs-iam-keycloak/values.yaml

also add new management/Health Port 

EW-961 update keycloak to 25.0.4

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json
src/themes/schulportal/login/login-update-password.ftl
src/themes/schulportal/login/resources/css/styles.css
src/themes/schulportal/login/template.ftl

The cancel Button on the update password form didnt work after updating the kc version. This is the fix for that.

adjust cancel button for new kc version

---

LICENCE

as has been discussed in: https://ticketsystem.dbildungscloud.de/browse/SPSH-148

DBP-952-change-license-file

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json

Set the editUsernameAllowed to true in order to allow the update of usernames.
https://ticketsystem.dbildungscloud.de/browse/SPSH-1037

SPSH-1037: Anpassung der Realm Konfiguration

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json

Changed claim to email

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-0000-improve-speed-of-pipeline

---

.github/workflows/create-release.yml

SPSH-1158-test-loadtest-drivers-gha-fixalso set docker target when creating a release

---

charts/dbildungs-iam-keycloak/dev-realm-spsh.json
charts/dbildungs-iam-keycloak/prod-realm-spsh.json
charts/dbildungs-iam-keycloak/templates/deployment.yaml
charts/dbildungs-iam-keycloak/templates/secret.yaml
charts/dbildungs-iam-keycloak/values.yaml

SPSH-1530 Load certificates from 1password

---

charts/dbildungs-iam-keycloak/templates/ingress2nd.yaml
charts/dbildungs-iam-keycloak/values.yaml

Add secondary ingress if enabled

Added 2nd ingress

---

charts/dbildungs-iam-keycloak/values.yaml

DBP-1147-fix-typo

---

charts/dbildungs-iam-keycloak/values.yaml

DBP-1204 corrected min available value

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

For full functionality of trivyignore file one needs to wait for https://github.com/dBildungsplattform/dbp-github-workflows/pull/30. However no breaking changes. 

DBP-1300-trivy-addition

---

.github/workflows/create-release.yml

It is open to discuss whether the fail_on_vulnerabilities should stay true or should be turned to false.

DBP-1264-improve-pipeline-remove all code tests before rollout - only trivy still active

---

charts/dbildungs-iam-keycloak/values.yaml

DBP-1494-removing pdb on infra and dev

---

src/themes/schulportal/login/login.ftl
src/themes/schulportal/login/template.ftl

SPSH-2539 added test ids for playwright tests

---

.github/workflows/chart-release-manual.yml
.github/workflows/create-release.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-1657-Update Sonarqube GHA to 5.3.1
